[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=3
startsecs=1
stdout_logfile=/var/log/supervisor/nginx-stdout.log
stderr_logfile=/var/log/supervisor/nginx-stderr.log

[program:profiler-server]
command=/opt/insight/backend/profiler_server --wsHost 127.0.0.1 --wsPort 9000
autostart=true
autorestart=true
startretries=3
startsecs=2
stdout_logfile=/var/log/supervisor/backend-stdout.log
stderr_logfile=/var/log/supervisor/backend-stderr.log
directory=/opt/insight/backend
environment=LD_LIBRARY_PATH="/opt/insight/backend"
